name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: leovanhaaren
          password: ${{ secrets.GITGUB_PACKAGES_PAT }}
      -
        name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/remindle/php-fpm:main
            ghcr.io/remindle/php-fpm:latest
